# Generated by Django 5.0.2 on 2024-07-12 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='end_time',
            new_name='Start_time',
        ),
    ]
